version: '3'
services:
  app:
    build: .
    ports:
      - 8081:8081
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
