// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	shema "goTSVParser/internal/shema"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx, r
func (_m *Service) GetAll(ctx context.Context, r shema.Request) ([][]shema.Tsv, error) {
	ret := _m.Called(ctx, r)

	var r0 [][]shema.Tsv
	if rf, ok := ret.Get(0).(func(context.Context, shema.Request) [][]shema.Tsv); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]shema.Tsv)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, shema.Request) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Worker provides a mock function with given fields: ctx
func (_m *Service) Worker(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
